version: '3'
services:
  # sonar:
  #   container_name: sonar-container
  #   image: sonarqube:lts-community
  #   ports:
  #    - "9000:9000"
  #   environment:
  #    - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
  #    - SONAR_JDBC_USERNAME=sonarqube
  #    - SONAR_JDBC_PASSWORD=sonarqube
  #   volumes:
  #    - sonar-data:/opt/sonarqube/data
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres-container
    image: postgres
    ports:
      - '5433:5432'
    environment:
     - POSTGRES_DB=sonarqube
     - POSTGRES_USER=sonarqube
     - POSTGRES_PASSWORD=sonarqube
    volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
  # sonar-data:
  postgres-data: