name: Build
on:
 pull_request:
   branches:
     - main
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres
      - name: Install dependencies
        run: npm install 
      - name: Set-up prisma
        run: cd src && npx prisma generate && npx prisma migrate dev --name init
      - name: Test and coverage
        run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}